name: Deploy Website Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip Lambda functions
        run: |
          zip -j ../lambda/visitor_counter.zip ../lambda/visitor_counter.py
          zip -j ../lambda/reset_weekly_counter.zip ../lambda/reset_weekly_counter.py

      - name: Init Terraform
        run: terraform init

      - name: Terraform Apply
        run: terraform apply --auto-approve